CREATE USER BOOKSTORE IDENTIFIED BY BOOKSSTORE;
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SEQUENCE TO BOOKSTORE;

--USER TABLE 유저
CREATE TABLE USERLIST(
USER_ID VARCHAR2(30) PRIMARY KEY,
USER_PWD VARCHAR2(30) NOT NULL, 
USER_NAME VARCHAR2(30), 
PHONE VARCHAR2(20) NOT NULL,
USER_POINT NUMBER(6) NOT NULL,
REG_DATE DATE,
GRADE VARCHAR2(9) DEFAULT '회원'
); 
 
INSERT INTO USERLIST VALUES ('K','1111','김현민', '010-1111-1111', 0, SYSDATE,'관리자'); 
INSERT INTO USERLIST VALUES ('C','1111','최량훈', '010-1111-1111', 10000, SYSDATE, DEFAULT);
INSERT INTO USERLIST VALUES ('P','1111','박기랑', '010-1111-1111', 100000, SYSDATE, DEFAULT);
INSERT INTO USERLIST VALUES ('L','1111','이경은', '010-1111-1111', 50000, SYSDATE, DEFAULT);
INSERT INTO USERLIST VALUES ('L2','1111','이창균', '010-1111-1111', 50000, SYSDATE, DEFAULT);

COMMIT;

SELECT * FROM USERLIST;
UPDATE USERLIST SET USER_POINT = '10000' WHERE USER_ID = 'P';

--BOOKS TABLE 도서
CREATE TABLE BOOKS(
BOOKS_ID VARCHAR2(20) PRIMARY KEY,
BOOKS_NAME VARCHAR2(50) NOT NULL,
WRITER VARCHAR(20) NOT NULL,
GENRE VARCHAR(20) NOT NULL, 
BOOKS_PRICE NUMBER(12) NOT NULL,
STOCK NUMBER(3)
);

INSERT INTO BOOKS VALUES('A01', '어린왕자', '생텍쥐페리', '동화', 7000, 10);
INSERT INTO BOOKS VALUES('A02','가시고기', '조창인', '소설', 6000,10);
INSERT INTO BOOKS VALUES('A03','소나기', '황순원', '소설', 7000,10);
INSERT INTO BOOKS VALUES('A04','동백꽃', '김유정', '소설', 7000,10);

SELECT*FROM BOOKS;

COMMIT;

--ORDERS TABLE 주문
CREATE TABLE ORDERS(
ORDER_ID NUMBER(5) PRIMARY KEY,
ORDER_DATE DATE NOT NULL,
USER_ID VARCHAR2(30)NOT NULL REFERENCES USERLIST(USER_ID) ,
--GRADE VARCHAR2(9) REFERENCES USERLIST(GRADE),
ADDRESS VARCHAR2(100) NOT NULL,
TOTAL_AMOUNT NUMBER(20) NOT NULL
);

DROP SEQUENCE ORDER_ID_SEQ;
CREATE SEQUENCE ORDER_ID_SEQ NOCACHE;


--ORDER_LINE TABLE 주문상세 
CREATE TABLE ORDER_LINE(
ORDER_LINE_ID NUMBER(5) PRIMARY KEY,
ORDER_ID NUMBER(5) NOT NULL REFERENCES ORDERS(ORDER_ID),
BOOKS_ID VARCHAR2(20) NOT NULL REFERENCES BOOKS(BOOKS_ID),
UNIT_PRICE NUMBER(12) NOT NULL,
QTY NUMBER(3) NOT NULL,
AMOUNT NUMBER(10) NOT NULL
);

CREATE SEQUENCE ORDER_LINE_ID_SEQ  NOCACHE;

--REGISTER BOOK TABLE 희망도서 
CREATE TABLE REGBOOK(
REG_NO NUMBER(3) PRIMARY KEY,
REG_NAME VARCHAR2(50) NOT NULL,
REG_WRITER VARCHAR2(30) NOT NULL,
REG_DATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE REG_NO_SEQ  NOCACHE;

CREATE TABLE NEW_BOOKS(
NEW_BOOKS_ID VARCHAR2(20) PRIMARY KEY,
NEW_BOOKS_NAME VARCHAR2(50) NOT NULL,
NEW_WRITER VARCHAR(20) NOT NULL,
NEW_GENRE VARCHAR(20) NOT NULL, 
NEW_BOOKS_PRICE NUMBER(12) NOT NULL,
NEW_STOCK NUMBER(3)
);

SELECT*FROM REGBOOK;
SELECT*FROM USERLIST;
SELECT*FROM BOOKS;
SELECT*FROM ORDERS;
SELECT*FROM ORDER_LINE;
SELECT* FROM NEW_BOOKS;

COMMIT;
rollback;

DROP TABLE REGBOOK;
DROP TABLE USERLIST;
DROP TABLE BOOKS;
DROP TABLE ORDERS;
DROP TABLE ORDER_LINE;
DROP TABLE NEW_BOOKS;



